/*
 * Licensed to the LookML Authors under one or more contributor
 * license agreements.  See the NOTICE file distributed with this
 * work for additional information regarding copyright ownership.
 * The LookML Authors license this file to you under the Apache
 * License, Version 2.0 (the "License"); you may not use this
 * file except in compliance with the License.  You may obtain a
 * copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied.  See the License for the specific
 * language governing permissions and limitations under the
 * License.
 */
package net.hydromatic.lookml.parse;

import net.hydromatic.lookml.ObjectHandler;
import net.hydromatic.lookml.Source;
import net.hydromatic.lookml.Sources;

import com.google.common.collect.ImmutableSortedSet;

import java.io.IOException;
import java.util.Set;

import static java.util.Objects.requireNonNull;

/** Utilities for parsing LookML. */
public class LookmlParsers {
  private LookmlParsers() {}

  /**
   * Parses a LookML string.
   *
   * <p>The parser is push-based, which means that rather than creating an
   * abstract syntax tree (AST) it generates a stream of events.
   *
   * @param handler Consumer of the events generated by the parser
   * @param config Parser configuration
   */
  public static void parse(ObjectHandler handler, Config config) {
    final Source source = config.source();
    final LookmlParserImpl parser;
    if (source.preferStream()) {
      try {
        parser = new LookmlParserImpl(source.inputStream());
      } catch (IOException e) {
        throw new RuntimeException(e);
      }
    } else {
      parser = new LookmlParserImpl(source.reader());
    }
    parser.config(config);
    try {
      parser.document(handler);
    } catch (ParseException e) {
      throw new RuntimeException(e);
    }
  }

  /** Returns the default configuration. */
  public static Config config() {
    return ConfigImpl.DEFAULT;
  }

  /** Configuration for parser. */
  public interface Config {
    /** Names of properties that are followed by a code block. */
    Set<String> codePropertyNames();

    /** Sets {@link #codePropertyNames()}. */
    Config withCodePropertyNames(Iterable<String> codePropertyNames);

    /** Location of the code to be parsed. */
    Source source();

    /** Sets {@link #source()}. */
    Config withSource(Source source);

    /** Number of spaces that a tab expands to. */
    int tabSize();

    /** Sets {@link #tabSize()}. */
    Config withTabSize(int tabSize);
  }

  /** Implementation of {@link Config}. */
  private static class ConfigImpl implements Config {
    private static final Config DEFAULT =
        new ConfigImpl(ImmutableSortedSet.of(), Sources.fromString(""), 1);

    private final Set<String> codePropertyNames;
    private final Source source;
    private final int tabSize;

    ConfigImpl(Iterable<String> codePropertyNames, Source source,
        int tabSize) {
      this.codePropertyNames = ImmutableSortedSet.copyOf(codePropertyNames);
      this.source = requireNonNull(source);
      this.tabSize = tabSize;
    }

    @Override public Set<String> codePropertyNames() {
      return codePropertyNames;
    }

    @Override public Config withCodePropertyNames(
        Iterable<String> codePropertyNames) {
      return new ConfigImpl(codePropertyNames, source, tabSize);
    }

    @Override public Source source() {
      return source;
    }

    @Override public Config withSource(Source source) {
      return new ConfigImpl(codePropertyNames, source, tabSize);
    }

    @Override public int tabSize() {
      return tabSize;
    }

    @Override public Config withTabSize(int tabSize) {
      return new ConfigImpl(codePropertyNames, source, tabSize);
    }
  }
}

// End LookmlParsers.java
